import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { AuthProvider } from "@/context/auth";
import AuthButtons from "@/components/custom/auth-buttons";
import { HomeIcon } from "lucide-react";
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import Image from "next/image";
import HomeLogo from "../../public/home-logo.svg";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Hot Homes",
  description: "Generated by create next app",
  icons: "/home-logo.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <AuthProvider>
          <nav className="bg-sky-950 text-white p-3 flex justify-between items-center">
            <Link
              href={"/"}
              className="flex items-center text-2xl tracking-wider gap-2 uppercase justify-end "
            >
              <div className="size-12 relative">
                <Image src={HomeLogo} alt="" fill className="object-center" />
              </div>
              <span className="mt-2">Hot Homes</span>
            </Link>
            <ul className="flex gap-6 items-center">
              <li>
                <Link
                  href="/property-search"
                  className="uppercase tracking-wider hover:underline"
                >
                  Property Search
                </Link>
              </li>
              <li>
                <AuthButtons />
              </li>
            </ul>
          </nav>
          {children}
          <Toaster richColors closeButton></Toaster>
        </AuthProvider>
      </body>
    </html>
  );
}
